### ISSUE TITLE
NPM dependencies can't be resolved

### ISSUE THREAD

**Issue by franz-josef-kaiser** [AdamQuadmon/generator-angular-silex#2]
When installing via npm, the following errors occur (`npm_debug.log`):

```
npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.7.1 wants generator-karma@~0.6.0
npm ERR! peerinvalid Peer generator-angular-silex@0.1.2 wants generator-karma@~0
.2.0

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "X:\\programdir\\nodejs\\node.exe" "X:\\programdir\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-angular-silex"
npm ERR! cwd X:\userdir\username
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     X:\userdir\username\npm-debug.log
npm ERR! not ok code 0
```

So the _karma_ dependency needs an update to `~0.6.0` in `package.json`.

**Comment by AdamQuadmon** [comment]
Hi @franz-josef-kaiser 
I'm sorry but I'm not working anymore on this project.
I just updated the readme cause I think there is a better way to do a silex/angular job.

This project is very old and I'm sure not only karma needs update.

If you want to keep using this stuff you can send a pull request or fork it and do the changes but I think it's a bad path to follow.

Let me know if you have any questions.

Thanks for trying this shit and for reporting the issue :+1:

**Comment by franz-josef-kaiser** [comment]
> Thanks for trying this shit

:D
